<?php 
  include_once('top.php');
  require_once('pesapal/OAuth.php');
  require_once('db/dbconnector.php');
  
  $api=empty($_POST['api']) ?'':$_POST['api'];
  if($api)
    $api = 'https://demo.pesapal.com';
  else
    $api = 'https://www.pesapal.com';
  
  $token = $params  = NULL;
  //$iframelink     = $api.'/api/PostPesapalDirectOrderV4';
  $iframelink = 'https://demo.pesapal.com/api/PostPesapalDirectOrderV4';
  
  //Kenyan keys
  //$consumer_key     = "0jQ2e53ON0VTI37dk0ZzZ9Y6sxw95yWE"; 
  //$consumer_secret  = "sJCuKMxmpY9+Lw8LM3PG6vydqw4=";
  //keys-sktytop demo
  $consumer_key = '7d1mIXGoetHVn/doW4RGXT+D+VonlamF';
  $consumer_secret = 'Wv/vUhcOd2yY8SqQfMu0ceQu+U8=';
   
  $signature_method = new OAuthSignatureMethod_HMAC_SHA1();
  $consumer       = new OAuthConsumer($consumer_key, $consumer_secret);
  
  //get form details
  $ref1=empty($_POST['reference'])?'':$_POST['reference'];
  if(!$ref1){
    $ref        =  str_repeat('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789',5);
    $_POST['reference'] =  substr(str_shuffle($ref),0,10);
  }
  
  $amount=empty($_POST['amount'])?'':$_POST['amount'];
  $amount     = str_replace(',','',$amount);$amount=(float)$amount; // remove thousands seperator if included
  $amount     = number_format($amount, 2); //format amount to 2 decimal places
  $desc       = empty($_POST['description'])?'xx':$_POST['description'];
  $type       = 'MERCHANT'; 
  $first_name   = empty($_POST['first_name'])?'':$_POST['first_name'];
  $last_name    = empty($_POST['last_name'])?'':$_POST['last_name'];
  $email      = empty($_POST['email'])?'':$_POST['email'];
  $phonenumber  = empty($_POST['phonenumber'])?'':$_POST['phonenumber'];
  //$currency     = $_POST['currency'];
  //$reference    = $_POST['reference']; //unique transaction id, generated by merchant
  $reference = uniqid() . md5( rand() . uniqid() );//unique order id of the transaction, generated by merchant
  $callback_url   = 'http://localhost/projects/redirect.php'; //URL user to be redirected to after payment

  ///
  // $desc = "Pesapal payment for DemosCAD token";
  // $type = "MERCHANT"; //default value = MERCHANT
  // $reference = uniqid() . md5( rand() . uniqid() );//unique order id of the transaction, generated by merchant
  // $first_name = $_GET['firstname'];
  // $last_name = $_GET['lastname'];
  // $email = $_GET['email'];
  //$phonenumber = '';//ONE of email or phonenumber is required
  ///
  
  //Record order in your database.
  $database = new pesapalDatabase();
  $database->store($_POST); 
    
  $post_xml = "<?xml version=\"1.0\" encoding=\"utf-8\"?>
           <PesapalDirectOrderInfo 
            xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" 
              xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" 
              Amount=\"".$amount."\" 
              Description=\"".$desc."\" 
              Type=\"".$type."\" 
              Reference=\"".$reference."\" 
              FirstName=\"".$first_name."\" 
              LastName=\"".$last_name."\" 
              Email=\"".$email."\" 
              PhoneNumber=\"".$phonenumber."\" 
              xmlns=\"http://www.pesapal.com\" />";
  $post_xml = htmlentities($post_xml);
  
  //post transaction to pesapal
  $iframe_src = OAuthRequest::from_consumer_and_token($consumer, $token, "GET", $iframelink, $params);
  $iframe_src->set_parameter("oauth_callback", $callback_url);
  $iframe_src->set_parameter("pesapal_request_data", $post_xml);
  $iframe_src->sign_request($signature_method, $consumer, $token);

  include('pay.php');
  include_once('top.php'); 

?>  
